name: mrz_parser
description: Parse MRZ (Machine Readable Zone) from identity documents.
version: 1.1.0
authors:
  - Anna Domashych <anna.domashych@gmail.com>
  - Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/mrz_parser

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: '>=0.12.42 <2.0.0'
  test_coverage: ^0.4.3
  collection: ^1.14.13
